=== brsnell/MX9001_Demo_USA/Packages/Beckhoff.TwinCAT.HMI.Scope.14.2.7758/runtimes/win/net472/TcHmiScope.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "position": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "x",
        "y"
      ]
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "width",
        "height"
      ]
    },
    "polygon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          }
        }
      }
    },
    "fullPolygon": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string"
        },
        "polygon": {
          "$ref": "#/definitions/polygon"
        }
      }
    },
    "grid": {
      "type": "object",
      "properties": {
        "ticks": {
          "type": "number"
        },
        "color": {
          "type": "string"
        },
        "lineWidth": {
          "type": "number"
        }
      },
      "required": [
        "ticks",
        "color",
        "lineWidth"
      ]
    },
    "overview": {
      "type": "object",
      "properties": {
        "visible": {
          "type": "boolean"
        },
        "dimensions": {
          "$ref": "#/definitions/dimensions"
        },
        "preferredSize": {
          "$ref": "#/definitions/dimensions"
        },
        "position": {
          "$ref": "#/definitions/position"
        },
        "canvas": {
          "type": "object",
          "properties": {
            "dimensions": {
              "$ref": "#/definitions/dimensions"
            },
            "position": {
              "$ref": "#/definitions/position"
            },
            "backgroundColor": {
              "type": "string"
            }
          }
        },
        "verticalAxis": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "visible": {
                "type": "boolean"
              },
              "visibleTicks": {
                "type": "boolean"
              },
              "dimensions": {
                "$ref": "#/definitions/dimensions"
              },
              "position": {
                "$ref": "#/definitions/position"
              },
              "color": {
                "type": "string"
              },
              "lineWidth": {
                "type": "number"
              },
              "headline": {
                "type": "object",
                "properties": {
                  "dimensions": {
                    "$ref": "#/definitions/dimensions"
                  },
                  "position": {
                    "$ref": "#/definitions/position"
                  },
                  "label": {
                    "type": "string"
                  },
                  "color": {
                    "type": "string"
                  },
                  "fontSize": {
                    "type": "number"
                  }
                },
                "required": [
                  "dimensions",
                  "position",
                  "label",
                  "color",
                  "fontSize"
                ]
              },
              "labels": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "dimensions": {
                      "$ref": "#/definitions/dimensions"
                    },
                    "position": {
                      "$ref": "#/definitions/position"
                    },
                    "label": {
                      "type": "string"
                    },
                    "color": {
                      "type": "string"
                    },
                    "fontSize": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "dimensions",
                    "position",
                    "label",
                    "color",
                    "fontSize"
                  ]
                }
              },
              "grid": {
                "type": "object",
                "properties": {
                  "ticks": {
                    "type": "number"
                  },
                  "color": {
                    "type": "string"
                  },
                  "lineWidth": {
                    "type": "number"
                  }
                },
                "required": [
                  "ticks",
                  "color",
                  "lineWidth"
                ]
              },
              "subGrid": {
                "type": "object",
                "properties": {
                  "ticks": {
                    "type": "number"
                  },
                  "color": {
                    "type": "string"
                  },
                  "lineWidth": {
                    "type": "number"
                  }
                },
                "required": [
                  "ticks",
                  "color",
                  "lineWidth"
                ]
              }
            },
            "required": [
              "visible",
              "dimensions",
              "position"
            ]
          }
        },
        "horizontalAxis": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "visible": {
                "type": "boolean"
              },
              "visibleTicks": {
                "type": "boolean"
              },
              "dimensions": {
                "$ref": "#/definitions/dimensions"
              },
              "position": {
                "$ref": "#/definitions/position"
              },
              "color": {
                "type": "string"
              },
              "lineWidth": {
                "type": "number"
              },
              "headline": {
                "type": "object",
                "properties": {
                  "dimensions": {
                    "$ref": "#/definitions/dimensions"
                  },
                  "position": {
                    "$ref": "#/definitions/position"
                  },
                  "label": {
                    "type": "string"
                  },
                  "color": {
                    "type": "string"
                  },
                  "fontSize": {
                    "type": "number"
                  }
                },
                "required": [
                  "dimensions",
                  "position",
                  "label",
                  "color",
                  "fontSize"
                ]
              },
              "labels": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "dimensions": {
                      "$ref": "#/definitions/dimensions"
                    },
                    "position": {
                      "$ref": "#/definitions/position"
                    },
                    "label": {
                      "type": "string"
                    },
                    "color": {
                      "type": "string"
                    },
                    "fontSize": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "dimensions",
                    "position",
                    "label",
                    "color",
                    "fontSize"
                  ]
                }
              },
              "grid": {
                "type": "object",
                "properties": {
                  "visible": {
                    "type": "boolean"
                  },
                  "ticks": {
                    "type": "number"
                  },
                  "color": {
                    "type": "string"
                  },
                  "lineWidth": {
                    "type": "number"
                  }
                },
                "required": [
                  "visible",
                  "ticks",
                  "color",
                  "lineWidth"
                ]
              },
              "subGrid": {
                "type": "object",
                "properties": {
                  "visible": {
                    "type": "boolean"
                  },
                  "ticks": {
                    "dimensions": {
                      "$ref": "#/definitions/dimensions"
                    },
                    "position": {
                      "$ref": "#/definitions/position"
                    },
                    "type": "number"
                  },
                  "color": {
                    "type": "string"
                  },
                  "lineWidth": {
                    "type": "number"
                  }
                },
                "required": [
                  "visible",
                  "ticks",
                  "color",
                  "lineWidth"
                ]
              }
            },
            "required": [
              "visible",
              "dimensions",
              "position"
            ]
          }
        },
        "graphs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "graphName": {
                "type": "string"
              },
              "graphType": {
                "type": "string"
              },
              "marks": {
                "type": "boolean"
              },
              "lineColor": {
                "type": "string"
              },
              "lineWidth": {
                "type": "string"
              },
              "markColor": {
                "type": "string"
              },
              "markWidth": {
                "type": "number"
              }
            },
            "required": [
              "graphType",
              "marks",
              "lineColor",
              "lineWidth",
              "lineStyle",
              "markColor",
              "markWidth"
            ]
          }
        }
      },
      "required": [
        "visible",
        "dimensions",
        "preferredSize",
        "position"
      ]
    }
  },
  "type": "object",
  "properties": {
    "TIMEOUT": {
      "configDescription": "DESC_TIMEOUT",
      "type": "string",
      "propertyOrder": 2,
      "format": "timespan",
      "default": "PT5S",
      "formatMinimum": "PT5S"
    },
    "CHUNKSIZE": {
      "configDescription": "DESC_CHUNKSIZE",
      "type": "integer",
      "propertyOrder": 2,
      "default": 1048576,
      "unit": "byte",
      "minimum": 1
    },
    "COMPRESSION": {
      "configDescription": "DESC_COMPRESSION",
      "type": "boolean",
      "propertyOrder": 2,
      "default": true
    },
    "scopeRecords": {
      "configDescription": "DESC_SCOPE_RECORDS",
      "visibility": "HideInEngineering",
      "readOnly": true,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "scopeConfigName": {
            "type": "string"
          },
          "headlessServerConnectionId": {
            "type": "string"
          },
          "headlessServer": {
            "type": "string"
          },
          "targetConnectionIds": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "target": {
                  "type": "string"
                },
                "targetNetId": {
                  "type": "string"
                },
                "connectionId": {
                  "type": "integer"
                }
              },
              "required": [
                "connectionId",
                "target",
                "targetNetId"
              ]
            }
          },
          "serverHandles": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "guid": {
                  "type": "string"
                },
                "serverHandle": {
                  "type": "integer"
                }
              },
              "required": [
                "guid",
                "serverHandle"
              ]
            }
          },
          "triggerHandles": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "guid": {
                  "type": "string"
                },
                "groupHandle": {
                  "type": "integer"
                },
                "clientTriggerHandle": {
                  "type": "integer"
                }
              },
              "required": [
                "guid",
                "groupHandle",
                "clientTriggerHandle"
              ]
            }
          }
        },
        "required": [
          "scopeConfigName",
          "headlessServerConnectionId",
          "serverHandles",
          "triggerHandles",
          "targetConnectionIds"
        ]
      }
    },
    "scopeConfigs": {
      "configDescription": "DESC_SCOPE_CONFIGS",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "AUTOSTART_RECORD": {
            "type": "boolean",
            "default": true
          },
          "CONFIG_SOURCE": {
            "visibility": "HideInEngineering",
            "type": "string",
            "enum": [
              "project",
              "file"
            ]
          },
          "CONFIG_PATH": {
            "visibility": "HideInEngineering",
            "type": "string"
          },
          "CONFIG_FILE": {
            "type": "string",
            "format": "base64"
          }
        },
        "required": [
          "CONFIG_FILE",
          "AUTOSTART_RECORD"
        ]
      }
    },
    "extensionHostMaxReloads": {
      "configDescription": "DESC_EXTENSION_HOST_MAX_RELOADS",
      "type": "integer",
      "minimum": 0,
      "default": 10
    },
    "extensionHostReloadInterval": {
      "configDescription": "DESC_EXTENSION_HOST_RELOAD_INTERVAL",
      "type": "string",
      "format": "timespan",
      "default": "PT10S"
    }
  },
  "required": [
    "TIMEOUT",
    "CHUNKSIZE",
    "COMPRESSION",
    "scopeConfigs",
    "scopeRecords"
  ]
}

=== brsnell/MX9001_Demo_USA/Musterkoffer_klein_HMI/Server/TcHmiScope/TcHmiScope.Config.default.json
{
    "CHUNKSIZE": 1048576,
    "COMPRESSION": true,
    "TIMEOUT": "PT5S",
    "scopeConfigs": {
        "Scope1": {
            "AUTOSTART_RECORD": true,
            "CONFIG_FILE": "77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjxTY29wZVByb2plY3QgQXNzZW1ibHlOYW1lPSJUd2luQ0FULk1lYXN1cmVtZW50LlNjb3BlLkFQSS5Nb2RlbCI+DQogIDxBY3RpdmVXb3JrZm9sZGVyUGF0aD5EOlxTb3VyY2VcR2l0SHViXE1YOTAwMV9EZW1vX1VTQVxTYW1wbGVDYXNlX1Njb3BlXFlUIFNjb3BlIFByb2plY3QgMjA5NzIyNjQ2MDwvQWN0aXZlV29ya2ZvbGRlclBhdGg+DQogIDxBdXRvRGVsZXRlQ2FwYWNpdHk+MDwvQXV0b0RlbGV0ZUNhcGFjaXR5Pg0KICA8QXV0b0RlbGV0ZU1vZGU+RGlzYWJsZWQ8L0F1dG9EZWxldGVNb2RlPg0KICA8QXV0b0RlbGV0ZU9sZGVyVGhhbj4wPC9BdXRvRGVsZXRlT2xkZXJUaGFuPg0KICA8QXV0b1Jlc3RhcnRSZWNvcmQ+ZmFsc2U8L0F1dG9SZXN0YXJ0UmVjb3JkPg0KICA8QXV0b1NhdmVFeHBvcnRDb25maWd1cmF0aW9uU3RyaW5nPiZsdDs/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9InV0Zi04Ij8mZ3Q7DQombHQ7RXhwb3J0Q29uZmlndXJhdGlvbiZndDsNCiAgJmx0O1NpbGVudCZndDtGYWxzZSZsdDsvU2lsZW50Jmd0Ow0KICAmbHQ7Rm9ybWF0X1Byb3BlcnRpZXMmZ3Q7DQoJJmx0O0NTVlByb3BlcnRpZXMmZ3Q7DQoJJmx0Oy9DU1ZQcm9wZXJ0aWVzJmd0Ow0KICAmbHQ7L0Zvcm1hdF9Qcm9wZXJ0aWVzJmd0Ow0KJmx0Oy9FeHBvcnRDb25maWd1cmF0aW9uJmd0Ow0KPC9BdXRvU2F2ZUV4cG9ydENvbmZpZ3VyYXRpb25TdHJpbmc+DQogIDxBdXRvU2F2ZUZpbGVOYW1lTWFzaz57U0NPUEV9X0F1dG9TYXZlX3tISF9tbV9zc308L0F1dG9TYXZlRmlsZU5hbWVNYXNrPg0KICA8QXV0b1NhdmVNb2RlPk5vbmU8L0F1dG9TYXZlTW9kZT4NCiAgPEF1dG9TYXZlUGF0aD4kU2NvcGVQcm9qZWN0JFxBdXRvU2F2ZTwvQXV0b1NhdmVQYXRoPg0KICA8Q29tbWVudCAvPg0KICA8RGlzcGxheUNvbG9yPkJsYWNrPC9EaXNwbGF5Q29sb3I+DQogIDxHdWlkPmIxZTY2Y2NkLWRmZTctNGVkMy1hN2I1LTEzYjcyYzgxYzFjMjwvR3VpZD4NCiAgPEhlYWRsZXNzU2VydmVyIC8+DQogIDxIZWFkbGVzc1NlcnZlckNvbm5lY3Rpb25JZD4wMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDA8L0hlYWRsZXNzU2VydmVyQ29ubmVjdGlvbklkPg0KICA8SW1hZ2VBdXRvRGVsZXRlQ2FwYWNpdHk+MDwvSW1hZ2VBdXRvRGVsZXRlQ2FwYWNpdHk+DQogIDxJbWFnZUF1dG9EZWxldGVPbGRlclRoYW4+MDwvSW1hZ2VBdXRvRGVsZXRlT2xkZXJUaGFuPg0KICA8SW1hZ2VzRGVsZXRlTW9kZT5EaXNhYmxlZDwvSW1hZ2VzRGVsZXRlTW9kZT4NCiAgPEtlZXBQcmV2aW91c0V4cG9ydHM+dHJ1ZTwvS2VlcFByZXZpb3VzRXhwb3J0cz4NCiAgPEtlZXBQcmV2aW91c0ltYWdlRXhwb3J0cz50cnVlPC9LZWVwUHJldmlvdXNJbWFnZUV4cG9ydHM+DQogIDxMYXlvdXQ+Jmx0Oz94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTE2Ij8mZ3Q7DQombHQ7TGF5b3V0Jmd0Ow0KICAmbHQ7V2luZG93IEd1aWQ9IjA4OTVlNzk5LTg0NTEtNGJiYS05YjQ0LWYwNDUxNTFmOGNmOCIgTGFzdEZvY3VzZWQ9IjEzNDAyNTk2MjQzNjcwMTYyMiIgRG9ja2VkU2l6ZT0iMjAwIiBQb3B1cFNpemU9IjAiIEZsb2F0aW5nTG9jYXRpb249Ii0xLCAtMSIgRmxvYXRpbmdTaXplPSI1NTAsIDQwMCIgTGFzdE9wZW5Eb2NrU2l0dWF0aW9uPSJEb2N1bWVudCIgTGFzdEZpeGVkRG9ja1NpdHVhdGlvbj0iRG9jdW1lbnQiIExhc3RGaXhlZERvY2tMb2NhdGlvbj0iUmlnaHQiIExhc3RGbG9hdGluZ1dpbmRvd0d1aWQ9IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIgTGFzdERvY2tDb250YWluZXJDb3VudD0iMCIgTGFzdERvY2tDb250YWluZXJJbmRleD0iMCIgRG9ja2VkV29ya2luZ1NpemU9IjI1MCwgNDAwIiBEb2NrZWRXaW5kb3dHcm91cEd1aWQ9IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIgRG9ja2VkSW5kZXhJbldpbmRvd0dyb3VwPSIwIiBEb2NrZWRTcGxpdFBhdGg9IjAiIERvY3VtZW50V29ya2luZ1NpemU9IjI1MCwgNDAwIiBEb2N1bWVudFdpbmRvd0dyb3VwR3VpZD0iNGRkNDkzYWYtZDc3YS00NTY4LTkxMTMtODZhNDBjZGJhMmI5IiBEb2N1bWVudEluZGV4SW5XaW5kb3dHcm91cD0iMCIgRG9jdW1lbnRTcGxpdFBhdGg9IjAiIEZsb2F0aW5nV29ya2luZ1NpemU9IjI1MCwgNDAwIiBGbG9hdGluZ1dpbmRvd0dyb3VwR3VpZD0iMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiBGbG9hdGluZ0luZGV4SW5XaW5kb3dHcm91cD0iMCIgRmxvYXRpbmdTcGxpdFBhdGg9IjAiIC8mZ3Q7DQogICZsdDtEb2N1bWVudENvbnRhaW5lciBEb2NrPSI1IiZndDsNCiAgICAmbHQ7U3BsaXRMYXlvdXRTeXN0ZW0gV29ya2luZ1NpemU9IjI1MCwgNDAwIiBTcGxpdE1vZGU9IjAiJmd0Ow0KICAgICAgJmx0O0NvbnRyb2xMYXlvdXRTeXN0ZW0gV29ya2luZ1NpemU9IjI1MCwgNDAwIiBHdWlkPSI0ZGQ0OTNhZi1kNzdhLTQ1NjgtOTExMy04NmE0MGNkYmEyYjkiIENvbGxhcHNlZD0iMCIgU2VsZWN0ZWRDb250cm9sPSIwODk1ZTc5OS04NDUxLTRiYmEtOWI0NC1mMDQ1MTUxZjhjZjgiJmd0Ow0KICAgICAgICAmbHQ7Q29udHJvbHMmZ3Q7DQogICAgICAgICAgJmx0O0NvbnRyb2wgR3VpZD0iMDg5NWU3OTktODQ1MS00YmJhLTliNDQtZjA0NTE1MWY4Y2Y4IiAvJmd0Ow0KICAgICAgICAmbHQ7L0NvbnRyb2xzJmd0Ow0KICAgICAgJmx0Oy9Db250cm9sTGF5b3V0U3lzdGVtJmd0Ow0KICAgICZsdDsvU3BsaXRMYXlvdXRTeXN0ZW0mZ3Q7DQogICZsdDsvRG9jdW1lbnRDb250YWluZXImZ3Q7DQombHQ7L0xheW91dCZndDs8L0xheW91dD4NCiAgPE1haW5TZXJ2ZXI+MTI3LjAuMC4xLjEuMTwvTWFpblNlcnZlcj4NCiAgPE5hbWU+U2NvcGUgUHJvamVjdDwvTmFtZT4NCiAgPFJlY29yZFRpbWU+NjAwMDAwMDAwMDwvUmVjb3JkVGltZT4NCiAgPFNlcnZlclZlcnNpb25zPg0KICAgIDxWZXJzaW9uPjQuNDkuMTAxLjA8L1ZlcnNpb24+DQogIDwvU2VydmVyVmVyc2lvbnM+DQogIDxTb3J0UHJpb3JpdHk+MTAwPC9Tb3J0UHJpb3JpdHk+DQogIDxTdG9wTW9kZT5BdXRvU3RvcDwvU3RvcE1vZGU+DQogIDxTdWJNZW1iZXI+DQogICAgPERhdGFQb29sIEFzc2VtYmx5TmFtZT0iVHdpbkNBVC5NZWFzdXJlbWVudC5TY29wZS5BUEkuTW9kZWwiPg0KICAgICAgPENvbW1lbnQgLz4NCiAgICAgIDxEaXNwbGF5Q29sb3I+QmxhY2s8L0Rpc3BsYXlDb2xvcj4NCiAgICAgIDxHdWlkPmFkZDExMzU3LTlkN2EtNDE3MC04MDVhLTVkMWU1NjJkYTI1MjwvR3VpZD4NCiAgICAgIDxOYW1lPkRhdGFQb29sPC9OYW1lPg0KICAgICAgPFNvcnRQcmlvcml0eT4wPC9Tb3J0UHJpb3JpdHk+DQogICAgICA8U3ViTWVtYmVyPg0KICAgICAgICA8QWRzQWNxdWlzaXRpb24gQXNzZW1ibHlOYW1lPSJUd2luQ0FULk1lYXN1cmVtZW50LlNjb3BlLkFQSS5Nb2RlbCI+DQogICAgICAgICAgPEFtc05ldElkPjE5Mi4xNjguNy4xODkuMS4xPC9BbXNOZXRJZD4NCiAgICAgICAgICA8QXJlYT5Mb2NhbDwvQXJlYT4NCiAgICAgICAgICA8QXJyYXlMZW5ndGg+MDwvQXJyYXlMZW5ndGg+DQogICAgICAgICAgPEFycmF5U3RhcnRJbmRleD4wPC9BcnJheVN0YXJ0SW5kZXg+DQogICAgICAgICAgPEJhc2VTYW1wbGVUaW1lPjEwMDAwMDwvQmFzZVNhbXBsZVRpbWU+DQogICAgICAgICAgPENoYW5uZWxTdHlsZUluZm9ybWF0aW9uIC8+DQogICAgICAgICAgPENvbW1lbnQ+PC9Db21tZW50Pg0KICAgICAgICAgIDxDb21wcmVzc2lvbk1vZGU+VW5jb21wcmVzc2VkPC9Db21wcmVzc2lvbk1vZGU+DQogICAgICAgICAgPENvbnRleHRNYXNrPjA8L0NvbnRleHRNYXNrPg0KICAgICAgICAgIDxEYXRhQWNjZXNzPg0KICAgICAgICAgICAgPERhdGFBY2Nlc3NNb2RlPg0KICAgICAgICAgICAgICA8U291cmNlPlR3aW5DQVQ8L1NvdXJjZT4NCiAgICAgICAgICAgICAgPFByb3RvY29sbD5BRFM8L1Byb3RvY29sbD4NCiAgICAgICAgICAgICAgPEZvcm1hdD5UY0JpbmFyeTwvRm9ybWF0Pg0KICAgICAgICAgICAgICA8VGltZUNvbnRleHQ+UHJlc2VudDwvVGltZUNvbnRleHQ+DQogICAgICAgICAgICAgIDxUaW1lVGFuZ2VJbmZvPg0KICAgICAgICAgICAgICAgIDxTdGFydFRpbWVTdGFtcD4wPC9TdGFydFRpbWVTdGFtcD4NCiAgICAgICAgICAgICAgICA8RW5kVGltZVN0YW1wPjA8L0VuZFRpbWVTdGFtcD4NCiAgICAgICAgICAgICAgPC9UaW1lVGFuZ2VJbmZvPg0KICAgICAgICAgICAgPC9EYXRhQWNjZXNzTW9kZT4NCiAgICAgICAgICA8L0RhdGFBY2Nlc3M+DQogICAgICAgICAgPERhdGFUeXBlPkJJVDwvRGF0YVR5cGU+DQogICAgICAgICAgPERpc3BsYXlDb2xvcj5CbGFjazwvRGlzcGxheUNvbG9yPg0KICAgICAgICAgIDxFbmFibGVkPnRydWU8L0VuYWJsZWQ+DQogICAgICAgICAgPEZpbGVIYW5kbGU+MDwvRmlsZUhhbmRsZT4NCiAgICAgICAgICA8Rm9yY2VPdmVyc2FtcGxpbmc+ZmFsc2U8L0ZvcmNlT3ZlcnNhbXBsaW5nPg0KICAgICAgICAgIDxHdWlkPmMwNWFmMzcxLThlOTItNDk3NS05NmNmLTRjNzAzOTk0MzcxYjwvR3VpZD4NCiAgICAgICAgICA8SW5kZXhHcm91cD42MTQ4ODwvSW5kZXhHcm91cD4NCiAgICAgICAgICA8SW5kZXhPZmZzZXQ+MzkwMjA4PC9JbmRleE9mZnNldD4NCiAgICAgICAgICA8SXNFdmVudD5mYWxzZTwvSXNFdmVudD4NCiAgICAgICAgICA8SXNIaXN0b3JpY2FsPmZhbHNlPC9Jc0hpc3RvcmljYWw+DQogICAgICAgICAgPElzVGltZWxpbmU+ZmFsc2U8L0lzVGltZWxpbmU+DQogICAgICAgICAgPE5hbWU+Yk91dHB1dENoMTwvTmFtZT4NCiAgICAgICAgICA8T3ZlcnNhbXBsZT4wPC9PdmVyc2FtcGxlPg0KICAgICAgICAgIDxSYXdVbml0Pg0KICAgICAgICAgICAgPFRyYW5zZm9ybWF0aW9uPg0KICAgICAgICAgICAgICA8QmFzZVVuaXRWYWx1ZT4wPC9CYXNlVW5pdFZhbHVlPg0KICAgICAgICAgICAgICA8TmFtZT5Ob25lPC9OYW1lPg0KICAgICAgICAgICAgICA8U2NhbGVGYWN0b3I+MTwvU2NhbGVGYWN0b3I+DQogICAgICAgICAgICAgIDxTb3VyY2VVbml0UHJlZml4Pm5vbmU8L1NvdXJjZVVuaXRQcmVmaXg+DQogICAgICAgICAgICAgIDxTb3VyY2VVbml0U3RyaW5nPjwvU291cmNlVW5pdFN0cmluZz4NCiAgICAgICAgICAgICAgPFN5bWJvbD4xPC9TeW1ib2w+DQogICAgICAgICAgICAgIDxUYXJnZXRVbml0U3RyaW5nPjwvVGFyZ2V0VW5pdFN0cmluZz4NCiAgICAgICAgICAgICAgPFRhcmdldFVuaXRWYWx1ZT4wPC9UYXJnZXRVbml0VmFsdWU+DQogICAgICAgICAgICA8L1RyYW5zZm9ybWF0aW9uPg0KICAgICAgICAgICAgPFVuaXQ+DQogICAgICAgICAgICAgIDxCYXNlVW5pdFN0cmluZz48L0Jhc2VVbml0U3RyaW5nPg0KICAgICAgICAgICAgICA8QmFzZVVuaXRWYWx1ZT4wPC9CYXNlVW5pdFZhbHVlPg0KICAgICAgICAgICAgICA8TmFtZUV4dGVuc2lvbj48L05hbWVFeHRlbnNpb24+DQogICAgICAgICAgICAgIDxPZmZzZXQ+MDwvT2Zmc2V0Pg0KICAgICAgICAgICAgICA8UHJlZml4Pm5vbmU8L1ByZWZpeD4NCiAgICAgICAgICAgICAgPFJldHVyblRleHQ+IChOb25lKSA8L1JldHVyblRleHQ+DQogICAgICAgICAgICAgIDxTY2FsZUZhY3Rvcj4xPC9TY2FsZUZhY3Rvcj4NCiAgICAgICAgICAgICAgPFN5bWJvbD48L1N5bWJvbD4NCiAgICAgICAgICAgIDwvVW5pdD4NCiAgICAgICAgICAgIDxVbml0T2Zmc2V0UmVzdWx0PjA8L1VuaXRPZmZzZXRSZXN1bHQ+DQogICAgICAgICAgICA8VW5pdFNjYWxlUmVzdWx0PjE8L1VuaXRTY2FsZVJlc3VsdD4NCiAgICAgICAgICAgIDxVc2VyVW5pdD4NCiAgICAgICAgICAgICAgPEJhc2VOYW1lPlVuaXRPZk9uZTwvQmFzZU5hbWU+DQogICAgICAgICAgICAgIDxCYXNlVW5pdFN0cmluZz48L0Jhc2VVbml0U3RyaW5nPg0KICAgICAgICAgICAgICA8QmFzZVVuaXRWYWx1ZT4wPC9CYXNlVW5pdFZhbHVlPg0KICAgICAgICAgICAgICA8TmFtZT5Ob25lPC9OYW1lPg0KICAgICAgICAgICAgICA8TmFtZUV4dGVuc2lvbj48L05hbWVFeHRlbnNpb24+DQogICAgICAgICAgICAgIDxPZmZzZXQ+MDwvT2Zmc2V0Pg0KICAgICAgICAgICAgICA8UHJlZml4Pm5vbmU8L1ByZWZpeD4NCiAgICAgICAgICAgICAgPFNjYWxlRmFjdG9yPjE8L1NjYWxlRmFjdG9yPg0KICAgICAgICAgICAgICA8U3ltYm9sPjwvU3ltYm9sPg0KICAgICAgICAgICAgICA8VXNlclByZWZpeD5ub25lPC9Vc2VyUHJlZml4Pg0KICAgICAgICAgICAgPC9Vc2VyVW5pdD4NCiAgICAgICAgICA8L1Jhd1VuaXQ+DQogICAgICAgICAgPFNhdmVPcHRpb24+SW5jbHVkZURhdGFJblNWRFg8L1NhdmVPcHRpb24+DQogICAgICAgICAgPFNlcnZlckhhbmRsZT4wPC9TZXJ2ZXJIYW5kbGU+DQogICAgICAgICAgPFNvcnRQcmlvcml0eT4xMDwvU29ydFByaW9yaXR5Pg0KICAgICAgICAgIDxTdWJBZHNBY3F1aXNpdGlvbiAvPg0KICAgICAgICAgIDxTdWJNZW1iZXI+DQogICAgICAgICAgICA8TmFtZVJlbGF0aW9uSW5mbyBBc3NlbWJseU5hbWU9IlR3aW5DQVQuTWVhc3VyZW1lbnQuU2NvcGUuQVBJLk1vZGVsIj4NCiAgICAgICAgICAgICAgPENvbW1lbnQgLz4NCiAgICAgICAgICAgICAgPERldGFpbExldmVsPg0KICAgICAgICAgICAgICAgIDxJbnQzMj4wPC9JbnQzMj4NCiAgICAgICAgICAgICAgPC9EZXRhaWxMZXZlbD4NCiAgICAgICAgICAgICAgPERpc3BsYXlDb2xvcj5CbGFjazwvRGlzcGxheUNvbG9yPg0KICAgICAgICAgICAgICA8R3VpZD5kNDljOWZmMS0yNDdlLTRjYzgtOGYyNC02YTkwZjNhNzQ3MTM8L0d1aWQ+DQogICAgICAgICAgICAgIDxOYW1lPk1lYXN1cmVtZW50TWVtYmVyQmFzZTwvTmFtZT4NCiAgICAgICAgICAgICAgPFNvcnRQcmlvcml0eT4xMDA8L1NvcnRQcmlvcml0eT4NCiAgICAgICAgICAgICAgPFRpdGxlPk1lYXN1cmVtZW50TWVtYmVyQmFzZTwvVGl0bGU+DQogICAgICAgICAgICAgIDxVc2VkTmFtZVR5cGU+RGV0YWlsTGV2ZWw8L1VzZWROYW1lVHlwZT4NCiAgICAgICAgICAgIDwvTmFtZVJlbGF0aW9uSW5mbz4NCiAgICAgICAgICA8L1N1Yk1lbWJlcj4NCiAgICAgICAgICA8U3ltYm9sQmFzZWQ+dHJ1ZTwvU3ltYm9sQmFzZWQ+DQogICAgICAgICAgPFN5bWJvbE5hbWU+TUFJTi5zdElvTW9kdWxTbG90OS5zdERPU091dHB1dHMuYk91dHB1dENoMTwvU3ltYm9sTmFtZT4NCiAgICAgICAgICA8VGFyZ2V0UG9ydD44NTE8L1RhcmdldFBvcnQ+DQogICAgICAgICAgPFRpbWVPZmZzZXQ+MDwvVGltZU9mZnNldD4NCiAgICAgICAgICA8VGl0bGU+TWVhc3VyZW1lbnRNZW1iZXJCYXNlPC9UaXRsZT4NCiAgICAgICAgICA8VXNlTG9jYWxTZXJ2ZXI+dHJ1ZTwvVXNlTG9jYWxTZXJ2ZXI+DQogICAgICAgICAg
